test:
    before_script:
        - install_clean.sh bundle-complete && apt-get update -qq && apt-get install -y -qq build-essential libsqlite3-dev libmariadbclient-dev-compat
    image: "camilstaps/clean:nightly"
    script:
        - bash ci-tests.bash
