test:
  image: "camilstaps/clean:nightly"
  before_script:
    - install_clean.sh bundle-complete
    - apt-get update -qq
    - apt-get install -y -qq build-essential libsqlite3-dev libmariadbclient-dev-compat
  script:
    - bash ci-tests.bash
  artifacts:
    when: always
    paths:
      - Tests/Unit/*-junit.xml
    reports:
      junit: Tests/Unit/*-junit.xml
