
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "itwc.patch.grid.GridViewLayout": "../../app/patch/grid/View.js",
  "Ext": "../../ext/src",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "itwc": "../../app"
});
Ext.ClassManager.addNameAlternateMappings({
  "itwc.component.edit.Int": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "itwc.controller.Controller": [],
  "itwc.component.view.String": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "itwc.component.edit.Date": [],
  "itwc.component.misc.Icon": [],
  "Ext.ux.DataView.DragSelector": [],
  "itwc.patch.grid.View": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "itwc.container.Container": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "itwc.component.edit.Editable": [],
  "itwc.component.view.Document": [],
  "Ext.ux.PreviewPlugin": [],
  "itwc.layout.component.edit.Code": [],
  "itwc.component.action.MenuButton": [],
  "itwc.patch.AbstractComponent": [],
  "Ext.ux.ajax.SimXhr": [],
  "itwc.component.action.ActionButton": [],
  "Ext.ux.event.RecorderManager": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.ux.ajax.Simlet": [],
  "itwc.container.Window": [],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "Ext.ux.event.Recorder": [],
  "itwc.container.Tasklet": [],
  "itwc.patch.grid.GridViewLayout": [],
  "Ext.ux.ajax.SimManager": [],
  "itwc.container.Panel": [],
  "itwc.component.view.Progress": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "itwc.component.choice.CheckboxGroup": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "itwc.component.misc.Splitter": [],
  "Ext.ux.TreePicker": [],
  "itwc.component.edit.Document": [],
  "itwc.component.edit.Time": [],
  "itwc.container.TabSet": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "itwc.component.edit.Code": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "itwc.component.view.Slider": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "itwc.component.misc.Label": [],
  "itwc.component.edit.Password": [],
  "itwc.component.edit.Decimal": [],
  "Ext.ux.GMapPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "itwc.component.choice.Grid": [],
  "itwc.component.action.ActionMenuItem": [],
  "Ext.ux.DataView.Animated": [],
  "itwc.component.view.Checkbox": [],
  "itwc.component.choice.Tree": [],
  "itwc.view.Viewport": [],
  "itwc.component.edit.Oryx": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "itwc.component.edit.Slider": [],
  "itwc.component.edit.EditButton": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "itwc.container.FieldSet": [],
  "itwc.component.edit.GoogleMap": [],
  "itwc.component.action.SubMenuItem": [],
  "Ext.ux.ToolbarDroppable": [],
  "itwc.container.HotkeyArea": [],
  "Ext.ux.event.Maker": [],
  "itwc.component.action.Menu": [],
  "itwc.container.TaskletPlaceholder": [],
  "itwc.component.choice.Dropdown": [],
  "itwc.component.edit.Note": [],
  "Ext.ux.DataView.Draggable": [],
  "itwc.component.choice.RadioGroup": [],
  "Ext.ux.TabCloseMenu": [],
  "itwc.container.TabItem": [],
  "itwc.layout.container.Box": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "itwc.component.view.HTML": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "itwc.component.misc.Tab": [],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "itwc.patch.layout.Context": [],
  "itwc.component.edit.String": [],
  "itwc.component.edit.Checkbox": []
});
Ext.ClassManager.addNameAliasMappings({
  "itwc.component.edit.Int": [
    "widget.itwc_edit_int"
  ],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "itwc.controller.Controller": [],
  "itwc.component.view.String": [
    "widget.itwc_view_string"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "itwc.component.edit.Date": [
    "widget.itwc_edit_date"
  ],
  "itwc.component.misc.Icon": [
    "widget.itwc_icon"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "itwc.patch.grid.View": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "itwc.container.Container": [
    "widget.itwc_container"
  ],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "itwc.component.edit.Editable": [],
  "itwc.component.view.Document": [
    "widget.itwc_view_document"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "itwc.layout.component.edit.Code": [
    "layout.itwc_edit_code"
  ],
  "itwc.component.action.MenuButton": [
    "widget.itwc_menubutton"
  ],
  "itwc.patch.AbstractComponent": [],
  "Ext.ux.ajax.SimXhr": [],
  "itwc.component.action.ActionButton": [
    "widget.itwc_actionbutton"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "itwc.container.Window": [
    "widget.itwc_window"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "Ext.ux.event.Recorder": [],
  "itwc.container.Tasklet": [
    "widget.itwc_tasklet"
  ],
  "itwc.patch.grid.GridViewLayout": [
    "layout.gridviewlayout"
  ],
  "Ext.ux.ajax.SimManager": [],
  "itwc.container.Panel": [
    "widget.itwc_panel"
  ],
  "itwc.component.view.Progress": [
    "widget.itwc_view_progress"
  ],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "itwc.component.choice.CheckboxGroup": [
    "widget.itwc_choice_checkboxgroup"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "itwc.component.misc.Splitter": [
    "widget.itwc_splitter"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "itwc.component.edit.Document": [
    "widget.itwc_edit_document"
  ],
  "itwc.component.edit.Time": [
    "widget.itwc_edit_time"
  ],
  "itwc.container.TabSet": [
    "widget.itwc_tabset"
  ],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "itwc.component.edit.Code": [
    "widget.itwc_edit_code"
  ],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "itwc.component.view.Slider": [
    "widget.itwc_view_slider"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "itwc.component.misc.Label": [
    "widget.itwc_label"
  ],
  "itwc.component.edit.Password": [
    "widget.itwc_edit_password"
  ],
  "itwc.component.edit.Decimal": [
    "widget.itwc_edit_decimal"
  ],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "itwc.component.choice.Grid": [
    "widget.itwc_choice_grid"
  ],
  "itwc.component.action.ActionMenuItem": [
    "widget.itwc_actionmenuitem"
  ],
  "Ext.ux.DataView.Animated": [],
  "itwc.component.view.Checkbox": [
    "widget.itwc_view_checkbox"
  ],
  "itwc.component.choice.Tree": [
    "widget.itwc_choice_tree"
  ],
  "itwc.view.Viewport": [],
  "itwc.component.edit.Oryx": [
    "widget.itwc_edit_oryx"
  ],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "itwc.component.edit.Slider": [
    "widget.itwc_edit_slider"
  ],
  "itwc.component.edit.EditButton": [
    "widget.itwc_editbutton"
  ],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Ext.ux.event.Player": [],
  "itwc.container.FieldSet": [
    "widget.itwc_fieldset"
  ],
  "itwc.component.edit.GoogleMap": [
    "widget.itwc_edit_googlemap"
  ],
  "itwc.component.action.SubMenuItem": [
    "widget.itwc_submenuitem"
  ],
  "Ext.ux.ToolbarDroppable": [],
  "itwc.container.HotkeyArea": [],
  "Ext.ux.event.Maker": [],
  "itwc.component.action.Menu": [
    "widget.itwc_menu"
  ],
  "itwc.container.TaskletPlaceholder": [
    "widget.itwc_tasklet_placeholder"
  ],
  "itwc.component.choice.Dropdown": [
    "widget.itwc_choice_dropdown"
  ],
  "itwc.component.edit.Note": [
    "widget.itwc_edit_note"
  ],
  "Ext.ux.DataView.Draggable": [],
  "itwc.component.choice.RadioGroup": [
    "widget.itwc_choice_radiogroup"
  ],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "itwc.container.TabItem": [
    "widget.itwc_tabitem"
  ],
  "itwc.layout.container.Box": [
    "layout.itwc_box"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "itwc.component.view.HTML": [
    "widget.itwc_view_html"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "itwc.component.misc.Tab": [
    "widget.itwc_tab"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "itwc.patch.layout.Context": [],
  "itwc.component.edit.String": [
    "widget.itwc_edit_string"
  ],
  "itwc.component.edit.Checkbox": [
    "widget.itwc_edit_checkbox"
  ]
});
